version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: qr-photo-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=qr_photo_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - qr-photo-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/qr_photo_db --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: qr-photo-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=qr_photo_db
      - SECRET_KEY=your-secret-key-change-in-production-docker-abc123def456
      - FRONTEND_URL=http://81.173.84.37:3000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - qr-photo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.simple
    container_name: qr-photo-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://81.173.84.37:8001
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - qr-photo-network

volumes:
  mongodb_data:
    driver: local

networks:
  qr-photo-network:
    driver: bridge